package com.example.domain

import com.example.model.FindingSeverity
import com.example.model.ScoreStatus
import com.example.model.SecurityScore
import com.example.model.VaultItem
import com.example.model.VaultType
import com.example.model.WatchtowerFinding
import com.example.security.EncryptionManager

object WatchtowerEngine {

    private const val NINETY_DAYS_MILLIS = 90L * 24 * 60 * 60 * 1000
    private const val ONE_YEAR_MILLIS = 365L * 24 * 60 * 60 * 1000

    fun analyze(items: List<VaultItem>): Pair<SecurityScore, List<WatchtowerFinding>> {
        val loginItems = items.filter { it.type == VaultType.LOGIN && it.password.isNotBlank() }
        val findings = mutableListOf<WatchtowerFinding>()

        var weakCount = 0
        var shortCount = 0
        var reusedCount = 0
        var oldPasswordCount = 0
        var missing2FaCount = 0

        val now = System.currentTimeMillis()

        // 1. Weak & Short password analysis
        for (item in loginItems) {
            val strength = EncryptionManager.calculateStrength(item.password)
            if (item.password.length < 8) {
                shortCount++
                findings.add(
                    WatchtowerFinding(
                        id = "short_${item.id}",
                        title = "Short Password (${item.name})",
                        explanation = "The password for '${item.name}' is only ${item.password.length} characters long, making it highly susceptible to brute-force dictionaries.",
                        recommendation = "Replace with a strong 16+ character password generated by Cyber Guard.",
                        severity = FindingSeverity.CRITICAL,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = listOf(item.id),
                        affectedAccountNames = listOf(item.name)
                    )
                )
            } else if (strength.score < 50) {
                weakCount++
                findings.add(
                    WatchtowerFinding(
                        id = "weak_${item.id}",
                        title = "Weak Password (${item.name})",
                        explanation = "The password for '${item.name}' has low entropy (${strength.entropyBits} bits) or uses predictable character patterns.",
                        recommendation = "Generate a cryptographically randomized high-entropy password.",
                        severity = FindingSeverity.WARNING,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = listOf(item.id),
                        affectedAccountNames = listOf(item.name)
                    )
                )
            }

            // Password Age Tracking
            val ageMillis = now - item.passwordLastChangedAt
            if (ageMillis > ONE_YEAR_MILLIS) {
                oldPasswordCount++
                val daysOld = (ageMillis / (24 * 60 * 60 * 1000)).toInt()
                findings.add(
                    WatchtowerFinding(
                        id = "old_year_${item.id}",
                        title = "Old Password: $daysOld Days Old (${item.name})",
                        explanation = "The password for '${item.name}' was set over a year ago. Passwords unchanged for long periods carry higher risk of historical exposure.",
                        recommendation = "Rotate this password to keep your credentials safe from legacy leaks.",
                        severity = FindingSeverity.CRITICAL,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = listOf(item.id),
                        affectedAccountNames = listOf(item.name)
                    )
                )
            } else if (ageMillis > NINETY_DAYS_MILLIS) {
                oldPasswordCount++
                val daysOld = (ageMillis / (24 * 60 * 60 * 1000)).toInt()
                findings.add(
                    WatchtowerFinding(
                        id = "old_90_${item.id}",
                        title = "Password Age: $daysOld Days (${item.name})",
                        explanation = "The password for '${item.name}' has not been changed in over 90 days.",
                        recommendation = "Consider rotating this credential or verifying that 2-Factor Authentication is active.",
                        severity = FindingSeverity.WARNING,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = listOf(item.id),
                        affectedAccountNames = listOf(item.name)
                    )
                )
            }
        }

        // 2. Reused password analysis (Exact match clusters)
        val passwordToItems = HashMap<String, MutableList<VaultItem>>()
        for (item in loginItems) {
            val list = passwordToItems.getOrPut(item.password) { mutableListOf() }
            list.add(item)
        }

        val reusedGroups = passwordToItems.filter { it.value.size > 1 }
        for ((_, group) in reusedGroups) {
            reusedCount += group.size
            val affectedNames = group.map { it.name }
            val affectedIds = group.map { it.id }
            val namesStr = affectedNames.joinToString(", ")

            for (item in group) {
                findings.add(
                    WatchtowerFinding(
                        id = "reused_${item.id}",
                        title = "Reused Password (${item.name})",
                        explanation = "'${item.name}' shares the same password with ${group.size - 1} other account(s): $namesStr. If one service is compromised, all linked accounts are exposed.",
                        recommendation = "Assign a distinct, randomly generated password to each account.",
                        severity = FindingSeverity.CRITICAL,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = affectedIds,
                        affectedAccountNames = affectedNames
                    )
                )
            }
        }

        // 3. Security Hygiene: Missing 2FA recommendations
        val sensitiveCategories = setOf("FINANCE", "BANKING", "SOCIAL", "WORK", "EMAIL", "MESSAGING")
        val sensitiveItems = items.filter {
            it.category.name in sensitiveCategories
        }
        for (item in sensitiveItems) {
            val has2faNote = item.notes.contains("2FA", ignoreCase = true) ||
                    item.notes.contains("MFA", ignoreCase = true) ||
                    item.notes.contains("OTP", ignoreCase = true) ||
                    item.tags.any { it.equals("2FA", ignoreCase = true) || it.equals("MFA", ignoreCase = true) }
            if (!has2faNote) {
                missing2FaCount++
                findings.add(
                    WatchtowerFinding(
                        id = "2fa_${item.id}",
                        title = "2FA Recommended for ${item.name}",
                        explanation = "High-value ${item.category.displayName} account without recorded Two-Factor Authentication.",
                        recommendation = "Enable 2FA (Authenticator App / Security Key) in this service's security settings.",
                        severity = FindingSeverity.INFO,
                        itemId = item.id,
                        itemName = item.name,
                        affectedItemIds = listOf(item.id),
                        affectedAccountNames = listOf(item.name)
                    )
                )
            }
        }

        // Calculate sub-metrics
        val totalLogins = loginItems.size
        val complexityScore = if (totalLogins == 0) 100 else {
            val totalEntropyScore = loginItems.sumOf { EncryptionManager.calculateStrength(it.password).score }
            (totalEntropyScore / totalLogins).coerceIn(10, 100)
        }

        val uniquenessScore = if (totalLogins == 0) 100 else {
            val uniqueCount = (totalLogins - reusedCount).coerceAtLeast(0)
            ((uniqueCount.toFloat() / totalLogins) * 100).toInt().coerceIn(0, 100)
        }

        val twoFactorScore = if (sensitiveItems.isEmpty()) 100 else {
            val with2fa = sensitiveItems.count { item ->
                item.notes.contains("2FA", ignoreCase = true) ||
                        item.notes.contains("MFA", ignoreCase = true) ||
                        item.tags.any { it.equals("2FA", ignoreCase = true) }
            }
            ((with2fa.toFloat() / sensitiveItems.size) * 100).toInt().coerceIn(20, 100)
        }

        val breachSafetyScore = 100

        val freshnessScore = if (loginItems.isEmpty()) 100 else {
            val freshCount = loginItems.count { (now - it.passwordLastChangedAt) < NINETY_DAYS_MILLIS }
            ((freshCount.toFloat() / loginItems.size) * 100).toInt().coerceIn(20, 100)
        }

        // Aggregate Security Score formula
        val score = if (totalLogins == 0) 100 else {
            val weighted = (
                    complexityScore * 0.30f +
                    uniquenessScore * 0.35f +
                    freshnessScore * 0.20f +
                    twoFactorScore * 0.15f
            ).toInt()
            weighted.coerceIn(10, 100)
        }

        val strongCount = (totalLogins - weakCount - shortCount - (reusedCount / 2)).coerceAtLeast(0)

        val status = when {
            totalLogins == 0 -> ScoreStatus.EXCELLENT
            score >= 90 -> ScoreStatus.EXCELLENT
            score >= 75 -> ScoreStatus.STRONG
            score >= 60 -> ScoreStatus.GOOD
            score >= 40 -> ScoreStatus.NEEDS_ACTION
            else -> ScoreStatus.CRITICAL
        }

        val securityScore = SecurityScore(
            score = score,
            status = status,
            totalPasswords = totalLogins,
            strongCount = strongCount,
            weakCount = weakCount + shortCount,
            reusedCount = reusedCount,
            shortCount = shortCount,
            oldPasswordCount = oldPasswordCount,
            missing2FaCount = missing2FaCount,
            complexityScore = complexityScore,
            uniquenessScore = uniquenessScore,
            twoFactorScore = twoFactorScore,
            breachSafetyScore = breachSafetyScore,
            freshnessScore = freshnessScore,
            lastBackupDate = "Today"
        )

        return Pair(securityScore, findings)
    }
}
